---
# tasks file for dotfiles

 - name: Clone dotfiles repository
   git:
     repo: git@github.com:kp9001/dotfiles.git
     dest: /var/home/centauri/
     clone: yes
     update: yes

 - name: Symlink bashrc
   file:
     src: "{{ user_home }}/dotfiles/shell/bashrc" 
     dest: "{{ user_home }}/.bashrc" 
     state: link

 - name: Symlink tmux theme
   file:
     src: "{{ user_home }}/dotfiles/tmux/theme_tmux.conf" 
     dest: "{{ user_home }}/.theme_tmux.conf" 
     state: link

 - name: Symlink tmux
   file:
     src: "{{ user_home }}/dotfiles/tmux/tmux.conf" 
     dest: "{{ user_home }}/.tmux.conf" 
     state: link

 - name: Symlink vimrc
   file:
     src: "{{ user_home }}/dotfiles/vim/vimrc" 
     dest: "{{ user_home }}/.vimrc" 
     state: link

 - name: Symlink alacritty
   file:
     src: "{{ user_home }}/dotfiles/alacritty" 
     dest: "{{ user_home }}/.config/alacritty" 
     state: link

 - name: Symlink rangeralacritty
   file:
     src: "{{ user_home }}/dotfiles/ranger" 
     dest: "{{ user_home }}/.config/ranger" 
     state: link

 - name: Symlink zathura
   file:
     src: "{{ user_home }}/dotfiles/zathura" 
     dest: "{{ user_home }}/.config/zathura" 
     state: link
